/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasPesquisa;

import DAO.DAOMotivo;
import DTO.Motivo;
import Reports.RepMotivos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telasCRUD.CrudMotivo;

/**
 *
 * @author jucabnu
 */
public class PesquisaMotivo extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaPadrao
     */
    public PesquisaMotivo() {
        initComponents();

        /*
        jComboBoxFiltro.removeAllItems();
        jComboBoxFiltro.addItem("Nome");
        jComboBoxFiltro.addItem("Login");
        */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotivos = new javax.swing.JTable();
        jButtonMostrar = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        botaoImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Motivos");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Buscar:");

        pesquisa.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisaFocusLost(evt);
            }
        });

        jTableMotivos.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTableMotivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cod", "Motivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMotivos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableMotivos);
        jTableMotivos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableMotivos.getColumnModel().getColumnCount() > 0) {
            jTableMotivos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jButtonMostrar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Filter.gif"))); // NOI18N
        jButtonMostrar.setMnemonic('m');
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonSelecionar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        jButtonSelecionar.setMnemonic('e');
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        jButtonSair.setMnemonic('s');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        botaoImprimir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print.gif"))); // NOI18N
        botaoImprimir.setMnemonic('r');
        botaoImprimir.setText("Relatório");
        botaoImprimir.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar)
                    .addComponent(jButtonSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(botaoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    javax.swing.JFrame jframe;

    public void instancia(javax.swing.JFrame jframe) {
        this.jframe = jframe;
    }

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        atualizaTabelaMotivos();
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        
                
        CrudMotivo tela = (CrudMotivo) this.jframe;
        tela.campoRecebe(jTableMotivos.getValueAt(jTableMotivos.getSelectedRow(), 0));        
        this.dispose();
        
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaFocusLost

        jButtonMostrarActionPerformed(null);

    }//GEN-LAST:event_pesquisaFocusLost

    private void botaoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirActionPerformed
        // TODO add your handling code here:

        try{            
            RepMotivos mm = new RepMotivos();
            mm.imprimir(DAOMotivo.getMotivos());            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);   
        }

    }//GEN-LAST:event_botaoImprimirActionPerformed

    
    public void atualizaTabelaMotivos() {
    
        ArrayList<Motivo> listaMotivos = DAO.DAOMotivo.getMotivosPorDesc(pesquisa.getText());
        insereTabelaMotivo(listaMotivos);
        
    }

    // método para criar a tabela (objeto tabela)
    //private void insereTabelaCliente(ArrayList<Cliente> listaCliente) {
    private void insereTabelaMotivo(ArrayList<Motivo> listaMotivos) {
        DefaultTableModel dtmc = new DefaultTableModel(); // criar o modelo da tabela

        Motivo mot;
        
        //definir colunas que a tabela vai conter
        dtmc.addColumn("Cod");
        dtmc.addColumn("Motivo");
        
        //preencher tabela com dados
        for (Object u : listaMotivos) {
            
            mot = (Motivo) u;
            String[] linha = new String[2]; // criar linha com 2 colunas, conforme tabela
            linha[0] = String.valueOf(mot.getCodmot());
            linha[1] = mot.getDesmot();
            dtmc.addRow(linha); // adicionando a linha criada

        }
        jTableMotivos.setModel(dtmc);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaMotivo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoImprimir;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMotivos;
    private javax.swing.JTextField pesquisa;
    // End of variables declaration//GEN-END:variables
}
