package telasCRUD;

import DAO.DAOMotivo;
import DAO.DAORnc;
import DAO.DAOSetor;
import DAO.DAOUsuario;
import DTO.Motivo;
import DTO.Rnc;
import DTO.RncAnalitico;
import DTO.Setor;
import DTO.Usuario;
import Principal.Datas;
import Principal.EnviaEmail;
import Reports.RepRNC;
import TelasPesquisa.PesquisaRnc;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jucabnu
 */
public class CrudRnc extends javax.swing.JFrame {

    /**
     * Creates new form crudCliente
     */
    private Usuario user;
     
    public CrudRnc() {
        initComponents();
        iniComb();
        desabilitaBotoes();
    }
    
    public CrudRnc(Usuario user) {
        this.user = user;
        initComponents();
        iniComb();
        desabilitaBotoes();
    }
    
    private void desabilitaBotoes(){
        if(!DAOUsuario.isAdm(user)){
            botaoExcluir.disable();
        }
    }
    
    private boolean travar(Rnc rnc, Usuario usu){
        // se situação diferente  de 0 e usuário NÃO é administrador
        return rnc.getSituacao() != 0 && !DAOUsuario.isAdm(usu);
    }
    
    private void travarEdicao(){
        
        jTextAreaIdeCausa.setEnabled(false);
        jTextAreaRespostaFinal.setEnabled(false);
        jTextFieldAreaResp.setEnabled(false);
        jTextFieldClienteFornecedor.setEnabled(false);
        jTextFieldDisposicao.setEnabled(false);
        jTextFieldFal.setEnabled(false);
        jTextFieldNotaFiscal.setEnabled(false);
        jTextFieldOrigem.setEnabled(false);
        jTextFieldProdutoServico.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldResponsavel.setEnabled(false);
        jTextFieldValor.setEnabled(false);
        jComboBoxLaboratorio.setEnabled(false);
        jComboBoxMotivo.setEnabled(false);
        jComboBoxSetor.setEnabled(false);
        jComboBoxSituacao.setEnabled(false);
    }
    
    private void iniComb(){

        // SIT
        
        jComboBoxSituacao.removeAllItems();
        jComboBoxSituacao.addItem("Em andamento"); //0
        jComboBoxSituacao.addItem("Procedente");   //1
        jComboBoxSituacao.addItem("Improcedente"); //2
        
        // LAB
        jComboBoxLaboratorio.removeAllItems();
        jComboBoxLaboratorio.addItem("Sim");
        jComboBoxLaboratorio.addItem("Não");
        
        // SETOR
        jComboBoxSetor.removeAllItems();
        ArrayList<Setor> setores = DAOSetor.getSetores();
        setores.forEach((s) -> {
            jComboBoxSetor.addItem(s.getNomset());
        }); 
        
        //MOTIVO
        jComboBoxMotivo.removeAllItems();
        ArrayList<Motivo> motivos = DAOMotivo.getMotivos();
        motivos.forEach((m) -> {
            jComboBoxMotivo.addItem(m.getDesmot());
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoGravar = new javax.swing.JButton();
        jLabelUsuarioResp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDataRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDataInicio = new javax.swing.JLabel();
        jLabelUltimaAlteracao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuarioUltimaAlt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDataFinal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRespostaFinal = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaIdeCausa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldOrigem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldClienteFornecedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProdutoServico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNotaFiscal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldFal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxLaboratorio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldDisposicao = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldAreaResp = new javax.swing.JTextField();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jComboBoxMotivo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Não Conformidade");

        campoCodigo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoFocusLost(evt);
            }
        });
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jLabelCPF.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelCPF.setText("Número RNC:");

        botaoPesquisar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        botaoPesquisar.setMnemonic('p');
        botaoPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                botaoPesquisarFocusLost(evt);
            }
        });
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        botaoSair.setMnemonic('s');
        botaoSair.setText("Sair");
        botaoSair.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoSair.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoSair.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoLimpar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abort.gif"))); // NOI18N
        botaoLimpar.setMnemonic('c');
        botaoLimpar.setText("Cancelar");
        botaoLimpar.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoGravar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        botaoGravar.setMnemonic('g');
        botaoGravar.setText("Gravar");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        jLabelUsuarioResp.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelUsuarioResp.setText(".");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Registro:");

        jLabelDataRegistro.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelDataRegistro.setText(".");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Início:");

        jLabelDataInicio.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelDataInicio.setText(".");

        jLabelUltimaAlteracao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelUltimaAlteracao.setText(".");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setText("Ultima Alteração:");

        jLabelUsuarioUltimaAlt.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelUsuarioUltimaAlt.setText(".");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setText("Finalização:");

        jLabelDataFinal.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelDataFinal.setText(".");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setText("Resposta final:");

        jTextAreaRespostaFinal.setColumns(20);
        jTextAreaRespostaFinal.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextAreaRespostaFinal.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRespostaFinal);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setText("Situação:");

        jComboBoxSituacao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setText("Identificação da causa:");

        jTextAreaIdeCausa.setColumns(20);
        jTextAreaIdeCausa.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextAreaIdeCausa.setRows(5);
        jScrollPane2.setViewportView(jTextAreaIdeCausa);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setText("Origem:");

        jTextFieldOrigem.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setText("Cliente/Fornecedor:");

        jTextFieldClienteFornecedor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldClienteFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteFornecedorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setText("Produto/Serviço:");

        jTextFieldProdutoServico.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setText("Setor destino:");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setText("Motivo:");

        jTextFieldQuantidade.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setText("Quantidade (kg):");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setText("No NFe:");

        jTextFieldNotaFiscal.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel15.setText("FAL:");

        jTextFieldFal.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel16.setText("Indicação do laboratório:");

        jComboBoxLaboratorio.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxLaboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel17.setText("Disposição/Indenização:");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel18.setText("Valor (R$):");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel19.setText("Área:");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel20.setText("Responsável:");

        jTextFieldDisposicao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jTextFieldValor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jTextFieldAreaResp.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jTextFieldResponsavel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jComboBoxSetor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxMotivo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.gif"))); // NOI18N
        botaoExcluir.setMnemonic('e');
        botaoExcluir.setText("Excluir");
        botaoExcluir.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoImprimir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eye.gif"))); // NOI18N
        botaoImprimir.setMnemonic('v');
        botaoImprimir.setText("Visualizar");
        botaoImprimir.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(botaoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCPF)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldFal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelDataInicio)
                                                .addComponent(jLabelUltimaAlteracao)
                                                .addComponent(jLabelDataFinal)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelDataRegistro)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelUsuarioUltimaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelUsuarioResp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldClienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldProdutoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDisposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAreaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCPF)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabelDataRegistro)
                                    .addComponent(jLabelUsuarioResp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDataInicio)
                                    .addComponent(jLabel2)))
                            .addComponent(botaoPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUltimaAlteracao)
                            .addComponent(jLabel3)
                            .addComponent(jLabelUsuarioUltimaAlt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelDataFinal))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProdutoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldClienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldFal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDisposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAreaResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGravar)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public Timestamp pegaDataAtual(){
        //String d;
        Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());
        
        //SimpleDateFormat formatar = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");        
        //d = formatar.format(date);
        //return d; 
        //Datas.converteData(date);
        //JOptionPane.showMessageDialog(null, date);
        return dataDeHoje;
    }
    
    public void campoRecebe(Object o) {
        campoCodigo.setText(String.valueOf(o));
    }

    //  **************************************************
    //  **************** GRAVAR / ALTERAR ****************
    //  **************************************************
    
    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed
    
        Rnc n = new Rnc();
        n.setClifor("");        

        try {
            if (campoCodigo.getText().equals("")) {
                // nada
                System.out.println("fez nada");
            } else {                
                
                n = DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText()));                
                System.out.println("pegou rnc pelo codigo");
            }
            
            if (n.getClifor().equals("")) {
                
                System.out.println("entrou em gravar");
                
                // GRAVAR : INSERT
                Rnc rnc = new Rnc();
                
                rnc.setCodusu(user.getCodusu());
                rnc.setDatreg(pegaDataAtual()); // método (TESTAR)
                rnc.setDatini(pegaDataAtual()); // data atual no insert
                rnc.setDatalt(pegaDataAtual()); // data atual no insert
                rnc.setAltusu(user.getCodusu());// usuário atual no insert
                rnc.setResfim(jTextAreaRespostaFinal.getText());
                rnc.setSituacao(jComboBoxSituacao.getSelectedIndex());
                
                rnc.setIdecau(jTextAreaIdeCausa.getText());
                rnc.setOricau(jTextFieldOrigem.getText());
                rnc.setClifor(jTextFieldClienteFornecedor.getText());
                rnc.setProser(jTextFieldProdutoServico.getText());
                rnc.setQtdrnc(Float.parseFloat(jTextFieldQuantidade.getText()));
                rnc.setNumnfe(Integer.parseInt(jTextFieldNotaFiscal.getText()));
                rnc.setNumfal(jTextFieldFal.getText());
                
                rnc.setCodset(DAOSetor.getSetorPorNome(String.valueOf(jComboBoxSetor.getSelectedItem())).getCodset());
                rnc.setCodmot(DAOMotivo.getMotivoPorDesc(String.valueOf(jComboBoxMotivo.getSelectedItem())).getCodmot());
                
                //AVISO LAB
                boolean lab = false;                
                if(String.valueOf(jComboBoxLaboratorio.getSelectedItem()).equals("Sim")){
                    lab = true;
                }                
                rnc.setLabind(lab);
                
                rnc.setDisind(jTextFieldDisposicao.getText());
                rnc.setValind(Float.parseFloat(jTextFieldValor.getText()));
                rnc.setAreind(jTextFieldAreaResp.getText());
                rnc.setResind(jTextFieldResponsavel.getText());
                
                DAORnc.inserir(rnc);
                
                //int num = DAORnc.getRncPeloNum(rnc.getNumrnc()).getNumrnc();
                //Rnc r = rnc;
                
                // AQUI VAI SER ENVIADO E-MAIL DE INCLUSÃO
                //EnviaEmail.Enviar(DAORnc.getRncPeloNum(num), "incluído");                
                //System.out.println(rnc.getNumrnc());
                
                
                EnviaEmail.Enviar(rnc, "incluído");
                
                JOptionPane.showMessageDialog(null, "Registro efetuado com sucesso!");
                
            } else {
                
                // DETERMINAR QUE, CASO ESTEJA SETADO A SITUAÇÃO COMO DIFERENTE DE 0
                // SOMENTE O ADMINISTRADOR PODERÁ EDITAR
                
                // ALTERAR : UPDATE
                
                System.out.println("entrou em atualizar");
                
                Rnc rnc = new Rnc();
                
                rnc.setNumrnc(Integer.parseInt(campoCodigo.getText()));
                rnc.setDatalt(pegaDataAtual());  // data atual no update
                rnc.setAltusu(user.getCodusu()); // usuário atual no insert
                
                rnc.setResfim(jTextAreaRespostaFinal.getText());
                
                rnc.setSituacao(jComboBoxSituacao.getSelectedIndex());
                rnc.setCodset(DAOSetor.getSetorPorNome(String.valueOf(jComboBoxSetor.getSelectedItem())).getCodset());
                rnc.setCodmot(DAOMotivo.getMotivoPorDesc(String.valueOf(jComboBoxMotivo.getSelectedItem())).getCodmot());
                
                //AVISO LAB
                boolean lab = false;                
                if(String.valueOf(jComboBoxLaboratorio.getSelectedItem()).equals("Sim")){
                    lab = true;
                }                
                rnc.setLabind(lab);
                                                
                rnc.setIdecau(jTextAreaIdeCausa.getText());
                rnc.setOricau(jTextFieldOrigem.getText());
                rnc.setClifor(jTextFieldClienteFornecedor.getText());
                rnc.setProser(jTextFieldProdutoServico.getText());
                rnc.setQtdrnc(Float.parseFloat(jTextFieldQuantidade.getText()));
                rnc.setNumnfe(Integer.parseInt(jTextFieldNotaFiscal.getText()));
                rnc.setNumfal(jTextFieldFal.getText());
                
                rnc.setDisind(jTextFieldDisposicao.getText());
                rnc.setValind(Float.parseFloat(jTextFieldValor.getText()));
                rnc.setAreind(jTextFieldAreaResp.getText());
                rnc.setResind(jTextFieldResponsavel.getText());
                                
                DAORnc.atualizar(rnc);      
                
                //rnc.setSituacao(jComboBoxSituacao.getSelectedIndex());
                if(jComboBoxSituacao.getSelectedIndex() != 0){
                    rnc.setDatfim(pegaDataAtual());
                    DAORnc.inserirDataFim(rnc);
                }
                
                // AQUI VAI SER ENVIADO E-MAIL DE ALTERAÇÃO
                EnviaEmail.Enviar(rnc, "alterado");
                
                JOptionPane.showMessageDialog(null, "As alterações foram gravadas com sucesso!");
                
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o registro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
                
        }
        
        
    }//GEN-LAST:event_botaoGravarActionPerformed

    //  **************************************************
    //  *************** CANCELAR / LIMPAR ****************
    //  **************************************************
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed

        // LIMPAR / CANCELAR
        // ---------------------------- ALTERAR O NOME DOS CAMPOS
        
        campoCodigo.setText("");            
        jLabelDataFinal.setText(".");
        jLabelDataInicio.setText(".");
        jLabelDataRegistro.setText(".");        
        jLabelUltimaAlteracao.setText(".");
        jLabelUsuarioResp.setText(".");
        jLabelUsuarioUltimaAlt.setText(".");
        jTextAreaIdeCausa.setText("");
        jTextAreaRespostaFinal.setText("");
        jTextFieldAreaResp.setText("");
        jTextFieldClienteFornecedor.setText("");
        jTextFieldDisposicao.setText("");
        jTextFieldFal.setText("");
        jTextFieldNotaFiscal.setText("");
        jTextFieldOrigem.setText("");
        jTextFieldProdutoServico.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldResponsavel.setText("");
        jTextFieldValor.setText("");
        jComboBoxLaboratorio.setSelectedIndex(0);
        jComboBoxMotivo.setSelectedIndex(0);
        jComboBoxSetor.setSelectedIndex(0);
        jComboBoxSituacao.setSelectedIndex(0);
        
    }//GEN-LAST:event_botaoLimparActionPerformed

    //  **************************************************
    //  ********************* FECHAR *********************
    //  **************************************************
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed

        this.dispose();

    }//GEN-LAST:event_botaoSairActionPerformed

    //  **************************************************
    //  ******************** PESQUISA *********************
    //  **************************************************
    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed

        PesquisaRnc tela = new PesquisaRnc();
        tela.instancia(this);
        tela.setVisible(true);
        
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoFocusLost

        // MOSTRAR RNC : SELECT (aparentemente tudo ok)
        try {
            if (campoCodigo.getText().equals("")) {
                // nada
            } else {
                
                Rnc n = DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText()));
                
                //jLabelDataFinal.setText(String.valueOf(n.getDatfim()));
                if(n.getDatfim() != null){
                    jLabelDataFinal.setText(Datas.converteData(n.getDatfim()));
                }else{
                    jLabelDataFinal.setText("-");
                }
                jLabelDataInicio.setText(Datas.converteData(n.getDatini()));                
                jLabelDataRegistro.setText(Datas.converteData(n.getDatreg()));        
                jLabelUltimaAlteracao.setText(Datas.converteData(n.getDatalt()));                
                
                jLabelUsuarioResp.setText(DAOUsuario.getUsuarioPeloCod(n.getCodusu()).getLogusu());
                jLabelUsuarioUltimaAlt.setText(DAOUsuario.getUsuarioPeloCod(n.getAltusu()).getLogusu());
                jTextAreaIdeCausa.setText(n.getIdecau());
                jTextAreaRespostaFinal.setText(n.getResfim());
                jTextFieldAreaResp.setText(n.getResind());
                jTextFieldClienteFornecedor.setText(n.getClifor());
                jTextFieldDisposicao.setText(n.getDisind());
                jTextFieldFal.setText(n.getNumfal());
                jTextFieldNotaFiscal.setText(String.valueOf(n.getNumnfe()));
                jTextFieldOrigem.setText(n.getOricau());
                jTextFieldProdutoServico.setText(n.getProser());
                jTextFieldQuantidade.setText(String.valueOf(n.getQtdrnc()));
                jTextFieldResponsavel.setText(n.getResind());
                jTextFieldValor.setText(String.valueOf(n.getValind()));
                jComboBoxSituacao.setSelectedIndex(n.getSituacao());
                
                if(n.isLabind()){
                    jComboBoxLaboratorio.setSelectedIndex(0);
                }else{
                    jComboBoxLaboratorio.setSelectedIndex(1);
                }
                jComboBoxMotivo.setSelectedItem(DAOMotivo.getMotivoPeloCod(n.getCodmot()).getDesmot());
                jComboBoxSetor.setSelectedItem(DAOSetor.getSetorPeloCod(n.getCodset()).getNomset());
                
                
                // travar edição para RNC fechada se usuário não é ADM
                if(travar(n, user)){
                    travarEdicao();
                }
                                
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Código inválido!"
                    + "\n"
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoCodigoFocusLost

    private void botaoPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoPesquisarFocusLost
        campoCodigoFocusLost(evt);
    }//GEN-LAST:event_botaoPesquisarFocusLost

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void jTextFieldClienteFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteFornecedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //  **************************************************
        //  *********** PREENCHER PARA TESTE  ****************
        //  **************************************************
        
        /*
        jLabelDataFinal.setText("");
        jLabelDataInicio.setText("");
        jLabelDataRegistro.setText("");        
        jLabelUltimaAlteracao.setText("");
        */
        //jLabelUsuarioResp.setText("");
        //jLabelUsuarioUltimaAlt.setText("");
        jTextAreaIdeCausa.setText("Desvio de temperatura no processo de tingimento.");
        jTextAreaRespostaFinal.setText("-");
        jTextFieldAreaResp.setText("Produção");
        jTextFieldClienteFornecedor.setText("Malhas IFC");
        jTextFieldDisposicao.setText("Reprocessar");
        jTextFieldFal.setText("124578");
        jTextFieldNotaFiscal.setText("321245");
        jTextFieldOrigem.setText("Tingimento");
        jTextFieldProdutoServico.setText("Malha comum");
        jTextFieldQuantidade.setText("156");
        jTextFieldResponsavel.setText("Renato");
        jTextFieldValor.setText("0");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed

        if(DAOUsuario.isAdm(user)){
            
            try {
                DAORnc.deletar(Integer.parseInt(campoCodigo.getText()));
                botaoLimparActionPerformed(evt); // limpa os campos
                JOptionPane.showMessageDialog(null, "RNC excluida com sucesso!");
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,
                    "Erro!" + "\n"
                    + "(Error Exception: " + e.getMessage());
                botaoLimparActionPerformed(evt);
            }    
            
        }else{
            JOptionPane.showMessageDialog(null, "Usuário precisa ser administrador!");
        }
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirActionPerformed
        // TODO add your handling code here:
        
        RncAnalitico r = new RncAnalitico();        
        r.setNumrnc(Integer.parseInt(campoCodigo.getText()));
        //r.setDatfim(DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText())).getDatfim());
        //r.setDatini(DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText())).getDatini());        
        //r.setDatreg(DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText())).getDatreg());
        //r.setDatalt(DAORnc.getRncPeloNum(Integer.parseInt(campoCodigo.getText())).getDatalt());
        
        r.setDatfim(jLabelDataFinal.getText());
        r.setDatini(jLabelDataInicio.getText());        
        r.setDatreg(jLabelDataRegistro.getText());
        r.setDatalt(jLabelUltimaAlteracao.getText());
        
        r.setNomusu_ger(jLabelUsuarioResp.getText());
        r.setNomusu_alt(jLabelUsuarioUltimaAlt.getText());
        r.setIdecau(jTextAreaIdeCausa.getText());
        r.setResfim(jTextAreaRespostaFinal.getText());
        r.setAreind(jTextFieldAreaResp.getText());
        r.setClifor(jTextFieldClienteFornecedor.getText());
        r.setDisind(jTextFieldDisposicao.getText());
        r.setNumfal(jTextFieldFal.getText());
        r.setNumnfe(Integer.parseInt(jTextFieldNotaFiscal.getText()));
        r.setOricau(jTextFieldOrigem.getText());
        r.setProser(jTextFieldProdutoServico.getText());
        r.setQtdrnc(Float.parseFloat(jTextFieldQuantidade.getText()));
        r.setResind(jTextFieldResponsavel.getText());
        r.setValind(Float.parseFloat(jTextFieldValor.getText()));
        r.setLabind(String.valueOf(jComboBoxLaboratorio.getSelectedItem()));
        r.setDesmot(String.valueOf(jComboBoxMotivo.getSelectedItem()));
        r.setNomset(String.valueOf(jComboBoxSetor.getSelectedItem()));
        r.setSituacao(String.valueOf(jComboBoxSituacao.getSelectedItem()));
        
        // tenho um objeto r com todo conteúdo pra enviar para o relatório
        
        ArrayList<RncAnalitico> lista = new ArrayList();
        lista.add(r);
        
        System.out.println(r);
        
        try{
            RepRNC rep = new RepRNC();            
            rep.imprimir(lista);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);   
        }
        
        
        
    }//GEN-LAST:event_botaoImprimirActionPerformed

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudRnc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudRnc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudRnc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudRnc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudRnc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoGravar;
    private javax.swing.JButton botaoImprimir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxLaboratorio;
    private javax.swing.JComboBox<String> jComboBoxMotivo;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelDataFinal;
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelDataRegistro;
    private javax.swing.JLabel jLabelUltimaAlteracao;
    private javax.swing.JLabel jLabelUsuarioResp;
    private javax.swing.JLabel jLabelUsuarioUltimaAlt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaIdeCausa;
    private javax.swing.JTextArea jTextAreaRespostaFinal;
    private javax.swing.JTextField jTextFieldAreaResp;
    private javax.swing.JTextField jTextFieldClienteFornecedor;
    private javax.swing.JTextField jTextFieldDisposicao;
    private javax.swing.JTextField jTextFieldFal;
    private javax.swing.JTextField jTextFieldNotaFiscal;
    private javax.swing.JTextField jTextFieldOrigem;
    private javax.swing.JTextField jTextFieldProdutoServico;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
