package telasCRUD;

import DAO.DAOMotivo;
import DTO.Motivo;
import TelasPesquisa.PesquisaMotivo;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author jucabnu
 */
public class CrudMotivo extends javax.swing.JFrame {

    public CrudMotivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Motivo");

        campoCodigo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoFocusLost(evt);
            }
        });
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jLabelCPF.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelCPF.setText("Código do Motivo:");

        jLabelNome.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelNome.setText("Descrição do Motivo:");

        campoDescricao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        botaoPesquisar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        botaoPesquisar.setMnemonic('p');
        botaoPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                botaoPesquisarFocusLost(evt);
            }
        });
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        botaoSair.setMnemonic('s');
        botaoSair.setText("Sair");
        botaoSair.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoSair.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoSair.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoLimpar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abort.gif"))); // NOI18N
        botaoLimpar.setMnemonic('c');
        botaoLimpar.setText("Cancelar");
        botaoLimpar.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.gif"))); // NOI18N
        botaoExcluir.setMnemonic('e');
        botaoExcluir.setText("Excluir");
        botaoExcluir.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoGravar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        botaoGravar.setMnemonic('g');
        botaoGravar.setText("Gravar");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCPF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 227, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(botaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void campoRecebe(Object o) {
        campoCodigo.setText(String.valueOf(o));
    }

    //  **************************************************
    //  **************** GRAVAR / ALTERAR ****************
    //  **************************************************
    
    
    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed

        Motivo m = new Motivo();
        m.setDesmot("");
        
        //Usuario u = new Usuario();
        //u.setNomusu("");

        try {
            if (campoCodigo.getText().equals("")) {                
                //botaoLimparActionPerformed(null);                
            } else {                
                m = DAOMotivo.getMotivoPeloCod(Integer.parseInt(campoCodigo.getText()));                                
            }
            
            if (m.getDesmot().equals("")) {
                
                // GRAVAR : INSERT
                Motivo mot = new Motivo();
                
                mot.setDesmot(campoDescricao.getText());
                DAOMotivo.inserir(mot);                
                JOptionPane.showMessageDialog(null, "Motivo cadastrado com sucesso!");
                
            } else {
                
                // ALTERAR : UPDATE
                                
                Motivo mot = new Motivo();
                mot.setCodmot(Integer.parseInt(campoCodigo.getText()));
                mot.setDesmot(campoDescricao.getText());
                DAOMotivo.atualizar(mot);
                JOptionPane.showMessageDialog(null, "As alterações foram gravadas com sucesso!");
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
        
    }//GEN-LAST:event_botaoGravarActionPerformed

    //  **************************************************
    //  *************** CANCELAR / LIMPAR ****************
    //  **************************************************
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed

        // LIMPAR / CANCELAR
        // ---------------------------- ALTERAR O NOME DOS CAMPOS
        
        campoCodigo.setText("");
        campoDescricao.setText("");
        
    }//GEN-LAST:event_botaoLimparActionPerformed

    //  **************************************************
    //  ********************* FECHAR *********************
    //  **************************************************
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed

        this.dispose();

    }//GEN-LAST:event_botaoSairActionPerformed

    //  **************************************************
    //  ********************* DELETE *********************
    //  **************************************************
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed

        
        try {
            
            DAOMotivo.deletar(Integer.parseInt(campoCodigo.getText()));            
            botaoLimparActionPerformed(evt); // limpa os campos
            JOptionPane.showMessageDialog(null, "Motivo excluido com sucesso!");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Erro!" + "\n"
                    + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(evt);
        }
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    //  **************************************************
    //  ******************** PESQUISA *********************
    //  **************************************************
    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed

        
        PesquisaMotivo tela = new PesquisaMotivo();
        tela.instancia(this);
        tela.setVisible(true);       

    }//GEN-LAST:event_botaoPesquisarActionPerformed

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoFocusLost

        // MOSTRAR CLIENTE : SELECT
        try {
            if (campoCodigo.getText().equals("")) {
                botaoLimparActionPerformed(null);
            } else {
                Motivo m = DAOMotivo.getMotivoPeloCod(Integer.parseInt(campoCodigo.getText()));
                campoDescricao.setText(m.getDesmot());
                
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Código inválido!"
                    + "\n"
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoCodigoFocusLost

    private void botaoPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoPesquisarFocusLost
        campoCodigoFocusLost(evt);
    }//GEN-LAST:event_botaoPesquisarFocusLost

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudMotivo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoGravar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelNome;
    // End of variables declaration//GEN-END:variables
}
