package telasCRUD;

import DAO.DAOUsuario;
import DTO.Usuario;
import TelasPesquisa.PesquisaUsuario;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jucabnu
 */
public class CrudUsuario extends javax.swing.JFrame {

    /**
     * Creates new form crudCliente
     */
    public CrudUsuario() {
        initComponents();
        
        jComboBoxTipo.removeAllItems();
        jComboBoxTipo.addItem("Usuário");
        jComboBoxTipo.addItem("Administrador");
        
        //System.out.println("len: " + jComboBoxTipo.getItemCount());
        //System.out.println(jComboBoxTipo.getItemAt(0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCodigo = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        campoLogin = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoGravar = new javax.swing.JButton();
        jLabelEndereco1 = new javax.swing.JLabel();
        jLabelEndereco2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jComboBoxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        campoCodigo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoFocusLost(evt);
            }
        });
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jLabelCPF.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelCPF.setText("Código:");

        jLabelNome.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelNome.setText("Nome:");

        campoNome.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabelTelefone.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelTelefone.setText("Email:");

        campoEmail.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        campoLogin.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabelEndereco.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelEndereco.setText("Login:");

        botaoPesquisar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        botaoPesquisar.setMnemonic('p');
        botaoPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                botaoPesquisarFocusLost(evt);
            }
        });
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        botaoSair.setMnemonic('s');
        botaoSair.setText("Sair");
        botaoSair.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoSair.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoSair.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoLimpar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abort.gif"))); // NOI18N
        botaoLimpar.setMnemonic('c');
        botaoLimpar.setText("Cancelar");
        botaoLimpar.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.gif"))); // NOI18N
        botaoExcluir.setMnemonic('e');
        botaoExcluir.setText("Excluir");
        botaoExcluir.setMaximumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setMinimumSize(new java.awt.Dimension(91, 25));
        botaoExcluir.setPreferredSize(new java.awt.Dimension(91, 25));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoGravar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        botaoGravar.setMnemonic('g');
        botaoGravar.setText("Gravar");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        jLabelEndereco1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelEndereco1.setText("Senha:");

        jLabelEndereco2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelEndereco2.setText("Tipo:");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jComboBoxTipo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEndereco1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEndereco2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(botaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco1)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEndereco2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(botaoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void campoRecebe(Object o) {
        campoCodigo.setText(String.valueOf(o));
    }

    //  **************************************************
    //  **************** GRAVAR / ALTERAR ****************
    //  **************************************************
    
    
    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed

        Usuario u = new Usuario();
        u.setNomusu("");

        try {
            if (campoCodigo.getText().equals("")) {
                // nada
                System.out.println("fez nada");
            } else {                
                u = DAOUsuario.getUsuarioPeloCod(Integer.parseInt(campoCodigo.getText()));
                System.out.println("pegou usuario pelo codigo");
            }
            
            if (u.getNomusu().equals("")) {
                
                System.out.println("entrou em gravar");
                
                // GRAVAR : INSERT
                
                Usuario usu = new Usuario();
                usu.setNomusu(campoNome.getText());
                usu.setEmausu(campoEmail.getText());
                usu.setLogusu(campoLogin.getText());
                usu.setPasusu(jPasswordField.getText());
                int tipo = 2;                
                if(String.valueOf(jComboBoxTipo.getSelectedItem()).equals("Administrador")){                
                    tipo = 1;
                }
                usu.setTipusu(tipo);
                
                if(DAOUsuario.duplicado(campoLogin.getText(), campoEmail.getText())){
                    JOptionPane.showMessageDialog(null, "Login/e-mail em uso! Escolha outro.");
                }else{
                    DAOUsuario.inserir(usu);                
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                }               
                
            } else {
                
                // ALTERAR : UPDATE
                System.out.println("entrou em atualizar");
                
                Usuario usu = new Usuario();
                usu.setCodusu(Integer.parseInt(campoCodigo.getText()));
                usu.setNomusu(campoNome.getText());
                usu.setEmausu(campoEmail.getText());
                usu.setLogusu(campoLogin.getText());
                usu.setPasusu(jPasswordField.getText());
                int tipo = 2;                
                if(String.valueOf(jComboBoxTipo.getSelectedItem()).equals("Administrador")){
                    tipo = 1;
                }
                System.out.println(String.valueOf(jComboBoxTipo.getSelectedItem()));
                usu.setTipusu(tipo);
                
                if(DAOUsuario.duplicado(campoLogin.getText(), campoEmail.getText())){
                    JOptionPane.showMessageDialog(null, "Login/e-mail em uso! Escolha outro.");
                }else{
                    DAOUsuario.atualizar(usu);                
                    JOptionPane.showMessageDialog(null, "As alterações foram gravadas com sucesso!");
                }    
                
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
        
        

    }//GEN-LAST:event_botaoGravarActionPerformed

    //  **************************************************
    //  *************** CANCELAR / LIMPAR ****************
    //  **************************************************
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed

        // LIMPAR / CANCELAR
        // ---------------------------- ALTERAR O NOME DOS CAMPOS
        
        campoCodigo.setText("");
        campoNome.setText("");
        campoEmail.setText("");
        campoLogin.setText("");
        jPasswordField.setText("");
        //campoTipo.setText("");
        
    }//GEN-LAST:event_botaoLimparActionPerformed

    //  **************************************************
    //  ********************* FECHAR *********************
    //  **************************************************
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed

        this.dispose();

    }//GEN-LAST:event_botaoSairActionPerformed

    //  **************************************************
    //  ********************* DELETE *********************
    //  **************************************************
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed

        
        try {
            
            DAOUsuario.deletar(Integer.parseInt(campoCodigo.getText()));            
            botaoLimparActionPerformed(evt); // limpa os campos
            JOptionPane.showMessageDialog(null, "Usuário excluido com sucesso!");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Erro!" + "\n"
                    + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(evt);
        }
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    //  **************************************************
    //  ******************** PESQUISA *********************
    //  **************************************************
    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed

        
        PesquisaUsuario tela = new PesquisaUsuario();
        tela.instancia(this);
        tela.setVisible(true);

    }//GEN-LAST:event_botaoPesquisarActionPerformed

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoFocusLost

        // MOSTRAR CLIENTE : SELECT
        try {
            if (campoCodigo.getText().equals("")) {
                botaoLimparActionPerformed(null);
            } else {
                
                Usuario u = DAOUsuario.getUsuarioPeloCod(Integer.parseInt(campoCodigo.getText()));
                
                campoNome.setText(u.getNomusu());
                campoEmail.setText(u.getEmausu());
                campoLogin.setText(u.getLogusu());
                jPasswordField.setText(u.getPasusu());
                
                if(u.getTipusu() == 1){
                    jComboBoxTipo.setSelectedIndex(1);                      
                }else{
                    jComboBoxTipo.setSelectedIndex(0);
                }
                
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Código inválido!"
                    + "\n"
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoCodigoFocusLost

    private void botaoPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botaoPesquisarFocusLost
        campoCodigoFocusLost(evt);
    }//GEN-LAST:event_botaoPesquisarFocusLost

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoGravar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEndereco1;
    private javax.swing.JLabel jLabelEndereco2;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
